// Plain-text data fixtures (.json .xml .log .ini .yaml .yml), source code and project files, and .tsv. The viewer shows them as text and never parses them.
import fs from "node:fs";
import path from "node:path";
import { GENERATED, LISTENER, SAFE_RULES, record, write } from "./lib.mjs";

const licence = "Generated by this repository; no third-party content";
const producer = "generator (text)";
const rec = (file, category, expect, extra = {}) =>
  record({ id: `data-${file.replace(/[/.]/g, "-")}`, file: `data/${file}`, format: path.extname(file).slice(1), category, producer, licence, expect, rules: SAFE_RULES, ...extra });

export function generateData({ large }) {
  write("data/simple.json", '{ "greeting": "Hello data", "count": 3, "items": [1, 2, 3] }\n');
  rec("simple.json", "simple", { result: "open", text: ["Hello data"] });
  write("data/complex.json", JSON.stringify({
    title: "Hello data", nested: { list: [{ id: "001", note: "leading zeros stay" }, { id: "002", rtl: "اردو سنڌي العربية" }], cjk: "中文 日本語 한국어" },
    escapes: "Tab\tquote\" backslash\\ unicode \u00e9", empty: null, big: 12345678901234567890
  }, null, 2) + "\n");
  rec("complex.json", "complex", { result: "open", text: ["leading zeros stay", "اردو"] });
  write("data/simple.xml", '<?xml version="1.0" encoding="UTF-8"?>\n<note><to>Reader</to><body>Hello data</body></note>\n');
  rec("simple.xml", "simple", { result: "open", text: ["<body>Hello data</body>"] });
  // Shown as text: the DOCTYPE and entity references must appear exactly as written, and nothing may be fetched.
  write("data/attack-xxe.xml", `<?xml version="1.0"?>\n<!DOCTYPE note [\n  <!ENTITY remote SYSTEM "${LISTENER}/xml-xxe/entity">\n  <!ENTITY local SYSTEM "file:///C:/Windows/win.ini">\n]>\n<note>Hello data &remote; &local;</note>\n`);
  rec("attack-xxe.xml", "attack", { result: "open", text: ["&remote;", "<!ENTITY remote SYSTEM"] }, { notes: "Must show the entity references literally; zero listener requests." });
  write("data/simple.log", "2026-09-29 10:00:01 INFO  Hello data\r\n2026-09-29 10:00:02 WARN  Disk space low\r\n2026-09-29 10:00:03 ERROR Something failed\r\n");
  rec("simple.log", "simple", { result: "open", text: ["Hello data"] });
  write("data/simple.ini", "; Settings file\r\n[General]\r\nGreeting=Hello data\r\nPath=C:\\Example\\Folder\r\n");
  rec("simple.ini", "simple", { result: "open", text: ["Greeting=Hello data"] });
  write("data/simple.yaml", "greeting: Hello data\nitems:\n  - one\n  - two\nanchor: &a { x: 1 }\nalias: *a\n");
  rec("simple.yaml", "simple", { result: "open", text: ["greeting: Hello data"] });
  write("data/simple.yml", "# Same format, other extension\ngreeting: Hello data\n");
  rec("simple.yml", "simple", { result: "open", text: ["greeting: Hello data"] });
  write("data/binary-named.json", Buffer.from([0x7b, 0x00, 0x01, 0x02, 0xff, 0xfe, 0x00, 0x7d]));
  rec("binary-named.json", "wrong-extension", { result: "error", error: "mismatch" }, { notes: "Binary data with a .json name." });

  // Source code and project files (0.8.0): shown as text, never run or built. The script and style sheet name the
  // test listener, so a viewer that ran or loaded them would be caught by the security smoke test.
  const code = {
    "simple.c": '#include <stdio.h>\n\nint main(void) {\n    printf("Hello code\\n");\n    return 0;\n}\n',
    "simple.h": "#ifndef HELLO_H\n#define HELLO_H\n/* Hello code */\nint hello(void);\n#endif\n",
    "simple.cs": 'namespace Sample;\n\npublic static class Program\n{\n    public static void Main() => System.Console.WriteLine("Hello code");\n}\n',
    "simple.java": 'public class Hello {\n    public static void main(String[] args) {\n        System.out.println("Hello code");\n    }\n}\n',
    "attack-script.js": `// Hello code: shown as text only; running it would reach the test listener.\nfetch("${LISTENER}/code-js/run");\ndocument.write('<img src="${LISTENER}/code-js/image">');\n`,
    "simple.vb": 'Module Hello\r\n    Sub Main()\r\n        Console.WriteLine("Hello code")\r\n    End Sub\r\nEnd Module\r\n',
    "attack-import.css": `/* Hello code */\n@import url("${LISTENER}/code-css/import");\nbody { background: url("${LISTENER}/code-css/image"); }\n`,
    "simple.php": '<?php\necho "Hello code";\n',
    "simple.asp": '<%\r\nResponse.Write "Hello code"\r\n%>\r\n',
    "simple.aspx": '<%@ Page Language="C#" %>\r\n<html><body><p>Hello code</p></body></html>\r\n',
    "simple.razor": '@page "/hello"\n<h1>Hello code</h1>\n@code {\n    private int count = 0;\n}\n',
    "app.config": '<?xml version="1.0" encoding="utf-8"?>\r\n<configuration>\r\n  <appSettings><add key="Greeting" value="Hello code" /></appSettings>\r\n</configuration>\r\n',
    "simple.csproj": '<Project Sdk="Microsoft.NET.Sdk">\r\n  <!-- Hello code -->\r\n  <PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>\r\n</Project>\r\n',
    "simple.sln": "﻿\r\nMicrosoft Visual Studio Solution File, Format Version 12.00\r\n# Hello code\r\nGlobal\r\nEndGlobal\r\n",
  };
  for (const [file, text] of Object.entries(code)) {
    const attack = file.startsWith("attack");
    write(`code/${file}`, text);
    record({ id: `code-${file.replace(/[/.]/g, "-")}`, file: `code/${file}`, format: path.extname(file).slice(1), category: attack ? "attack" : "simple",
      producer, licence, expect: { result: "open", text: ["Hello code"] }, rules: SAFE_RULES, ...(attack ? { notes: "Must be shown as text; zero listener requests." } : {}) });
  }
  write("code/binary-named.cs", Buffer.from([0x4d, 0x5a, 0x90, 0x00, 0x03, 0x00, 0x00, 0x00]));
  record({ id: "code-binary-named-cs", file: "code/binary-named.cs", format: "cs", category: "wrong-extension", producer, licence,
    expect: { result: "error", error: "mismatch" }, rules: SAFE_RULES, notes: "A program file with a .cs name." });

  // Tab-separated values (0.8.0): the grid splits on tabs even where commas appear in fields.
  write("data/simple.tsv", "Name\tValue\tNote\r\nHello data\t001\tleading zero, kept\r\nSecond\t2\tcomma, inside\r\n");
  rec("simple.tsv", "simple", { result: "open", text: ["Hello data", "001"] });

  if (large) {
    // About 60 MB of JSON lines: shown through the disk-backed line view.
    fs.mkdirSync(GENERATED, { recursive: true });
    const out = fs.openSync(path.join(GENERATED, "data-large.json"), "w");
    fs.writeSync(out, "[\n");
    for (let i = 0; i < 600000; i++) fs.writeSync(out, `  { "row": ${i}, "id": "${String(i).padStart(7, "0")}", "note": "Hello data row ${i}" }${i < 599999 ? "," : ""}\n`);
    fs.writeSync(out, "]\n"); fs.closeSync(out);
    record({ id: "data-large-json", file: "generated/data-large.json", format: "json", category: "large", generated: true, producer, licence, expect: { result: "open", text: ["Hello data row 0"] }, rules: SAFE_RULES });
  }
}
