// Plain-text data fixtures (.json .xml .log .ini .yaml .yml). The viewer shows them as text and never parses them.
import fs from "node:fs";
import path from "node:path";
import { GENERATED, LISTENER, SAFE_RULES, record, write } from "./lib.mjs";

const licence = "Generated by this repository; no third-party content";
const producer = "generator (text)";
const rec = (file, category, expect, extra = {}) =>
  record({ id: `data-${file.replace(/[/.]/g, "-")}`, file: `data/${file}`, format: path.extname(file).slice(1), category, producer, licence, expect, rules: SAFE_RULES, ...extra });

export function generateData({ large }) {
  write("data/simple.json", '{ "greeting": "Hello data", "count": 3, "items": [1, 2, 3] }\n');
  rec("simple.json", "simple", { result: "open", text: ["Hello data"] });
  write("data/complex.json", JSON.stringify({
    title: "Hello data", nested: { list: [{ id: "001", note: "leading zeros stay" }, { id: "002", rtl: "اردو سنڌي العربية" }], cjk: "中文 日本語 한국어" },
    escapes: "Tab\tquote\" backslash\\ unicode \u00e9", empty: null, big: 12345678901234567890
  }, null, 2) + "\n");
  rec("complex.json", "complex", { result: "open", text: ["leading zeros stay", "اردو"] });
  write("data/simple.xml", '<?xml version="1.0" encoding="UTF-8"?>\n<note><to>Reader</to><body>Hello data</body></note>\n');
  rec("simple.xml", "simple", { result: "open", text: ["<body>Hello data</body>"] });
  // Shown as text: the DOCTYPE and entity references must appear exactly as written, and nothing may be fetched.
  write("data/attack-xxe.xml", `<?xml version="1.0"?>\n<!DOCTYPE note [\n  <!ENTITY remote SYSTEM "${LISTENER}/xml-xxe/entity">\n  <!ENTITY local SYSTEM "file:///C:/Windows/win.ini">\n]>\n<note>Hello data &remote; &local;</note>\n`);
  rec("attack-xxe.xml", "attack", { result: "open", text: ["&remote;", "<!ENTITY remote SYSTEM"] }, { notes: "Must show the entity references literally; zero listener requests." });
  write("data/simple.log", "2026-09-29 10:00:01 INFO  Hello data\r\n2026-09-29 10:00:02 WARN  Disk space low\r\n2026-09-29 10:00:03 ERROR Something failed\r\n");
  rec("simple.log", "simple", { result: "open", text: ["Hello data"] });
  write("data/simple.ini", "; Settings file\r\n[General]\r\nGreeting=Hello data\r\nPath=C:\\Example\\Folder\r\n");
  rec("simple.ini", "simple", { result: "open", text: ["Greeting=Hello data"] });
  write("data/simple.yaml", "greeting: Hello data\nitems:\n  - one\n  - two\nanchor: &a { x: 1 }\nalias: *a\n");
  rec("simple.yaml", "simple", { result: "open", text: ["greeting: Hello data"] });
  write("data/simple.yml", "# Same format, other extension\ngreeting: Hello data\n");
  rec("simple.yml", "simple", { result: "open", text: ["greeting: Hello data"] });
  write("data/binary-named.json", Buffer.from([0x7b, 0x00, 0x01, 0x02, 0xff, 0xfe, 0x00, 0x7d]));
  rec("binary-named.json", "wrong-extension", { result: "error", error: "mismatch" }, { notes: "Binary data with a .json name." });

  if (large) {
    // About 60 MB of JSON lines: shown through the disk-backed line view.
    fs.mkdirSync(GENERATED, { recursive: true });
    const out = fs.openSync(path.join(GENERATED, "data-large.json"), "w");
    fs.writeSync(out, "[\n");
    for (let i = 0; i < 600000; i++) fs.writeSync(out, `  { "row": ${i}, "id": "${String(i).padStart(7, "0")}", "note": "Hello data row ${i}" }${i < 599999 ? "," : ""}\n`);
    fs.writeSync(out, "]\n"); fs.closeSync(out);
    record({ id: "data-large-json", file: "generated/data-large.json", format: "json", category: "large", generated: true, producer, licence, expect: { result: "open", text: ["Hello data row 0"] }, rules: SAFE_RULES });
  }
}
