// Picture fixtures. Producers are independent of the viewer's decoders (WebView2/Chromium): this generator's own PNG,
// BMP and ICO writer; Windows GDI+ for JPEG, GIF and TIFF; libavif and libwebp (jSquash WebAssembly builds) for AVIF
// and WebP; SVG written as text.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import zlib from "node:zlib";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { CORPUS, GENERATED, LISTENER, WEBDAV_UNC, SAFE_RULES, packageVersion, record, write } from "./lib.mjs";
import encodeAvif, { init as initAvif } from "@jsquash/avif/encode.js";
import encodeWebp, { init as initWebp } from "@jsquash/webp/encode.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const licence = "Generated by this repository; no third-party content";
const own = "generator's own PNG/BMP/ICO writer (Node)";
const gdi = "Windows GDI+ (System.Drawing), from the generator's PNG";
const jsquash = name => `@jsquash/${name} ${packageVersion(`@jsquash/${name}`)} (${name === "avif" ? "libavif" : "libwebp"} WebAssembly)`;

// RGBA pixels from a function of (x, y).
function pixels(width, height, pixel) {
  const data = new Uint8ClampedArray(width * height * 4);
  for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) data.set(pixel(x, y), (y * width + x) * 4);
  return { data, width, height, colorSpace: "srgb" };
}

function pngRgba({ data, width, height }) {
  const raw = Buffer.alloc((width * 4 + 1) * height);
  for (let y = 0; y < height; y++) Buffer.from(data.buffer, y * width * 4, width * 4).copy(raw, y * (width * 4 + 1) + 1);
  const chunk = (type, body) => {
    const length = Buffer.alloc(4); length.writeUInt32BE(body.length);
    const typed = Buffer.concat([Buffer.from(type, "ascii"), body]);
    const crc = Buffer.alloc(4); crc.writeUInt32BE(zlib.crc32(typed) >>> 0);
    return Buffer.concat([length, typed, crc]);
  };
  const ihdr = Buffer.alloc(13); ihdr.writeUInt32BE(width, 0); ihdr.writeUInt32BE(height, 4); ihdr[8] = 8; ihdr[9] = 6;
  return Buffer.concat([Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", ihdr), chunk("IDAT", zlib.deflateSync(raw, { level: 9 })), chunk("IEND", Buffer.alloc(0))]);
}

// 24-bit bottom-up BMP (alpha dropped).
function bmp({ data, width, height }) {
  const stride = Math.ceil(width * 3 / 4) * 4, size = 54 + stride * height, out = Buffer.alloc(size);
  out.write("BM", 0); out.writeUInt32LE(size, 2); out.writeUInt32LE(54, 10); out.writeUInt32LE(40, 14);
  out.writeInt32LE(width, 18); out.writeInt32LE(height, 22); out.writeUInt16LE(1, 26); out.writeUInt16LE(24, 28); out.writeUInt32LE(stride * height, 34);
  for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) {
    const s = ((height - 1 - y) * width + x) * 4, d = 54 + y * stride + x * 3;
    out[d] = data[s + 2]; out[d + 1] = data[s + 1]; out[d + 2] = data[s];
  }
  return out;
}

// An icon holding one PNG image (Windows Vista and later).
function ico(png, size) {
  const head = Buffer.alloc(22);
  head.writeUInt16LE(1, 2); head.writeUInt16LE(1, 4);
  head[6] = size >= 256 ? 0 : size; head[7] = size >= 256 ? 0 : size;
  head.writeUInt16LE(1, 10); head.writeUInt16LE(32, 12); head.writeUInt32LE(png.length, 14); head.writeUInt32LE(22, 18);
  return Buffer.concat([head, png]);
}

function viaGdi(png, format, extra = []) {
  const folder = fs.mkdtempSync(path.join(os.tmpdir(), "pv-gdi-"));
  try {
    const input = path.join(folder, "in.png"), output = path.join(folder, "out");
    fs.writeFileSync(input, png);
    execFileSync("powershell.exe", ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", path.join(here, "gdiplus.ps1"), input, output, format, ...extra.map(String)]);
    return fs.readFileSync(output);
  } finally { fs.rmSync(folder, { recursive: true, force: true }); }
}

const gradient = (w, h) => pixels(w, h, (x, y) => [Math.round(255 * x / w), Math.round(255 * y / h), 160, 255]);
// Transparent corners, coloured rings and a diagonal band, so decoding errors and wrong alpha are visible.
const complexArt = (w, h) => pixels(w, h, (x, y) => {
  const dx = x - w / 2, dy = y - h / 2, r = Math.hypot(dx, dy), ring = Math.floor(r / 24) % 3;
  const alpha = r > Math.min(w, h) * 0.48 ? 0 : 255;
  const band = Math.abs(x - y * w / h) < 18;
  return band ? [20, 20, 20, alpha] : [[217, 83, 79], [92, 184, 92], [66, 139, 202]][ring].concat(alpha);
});
const noise = (w, h) => pixels(w, h, (x, y) => { const v = (x * 7919 + y * 104729) % 251; return [v, (v * 3) % 256, (x ^ y) & 255, 255]; });

const rec = (file, category, expect, producer, extra = {}) =>
  record({ id: `image-${file.replace(/[/.]/g, "-")}`, file: `images/${file}`, format: path.extname(file).slice(1), category, producer, licence, expect, rules: SAFE_RULES, ...extra });
const opens = (format, width, height) => ({ result: "open", format, width, height });

export async function generateImages({ large }) {
  const base = path.join(here, "node_modules", "@jsquash");
  await initAvif(await WebAssembly.compile(fs.readFileSync(path.join(base, "avif", "codec", "enc", "avif_enc.wasm"))));
  await initWebp(await WebAssembly.compile(fs.readFileSync(path.join(base, "webp", "codec", "enc", "webp_enc.wasm"))));

  const simple = gradient(320, 200), simplePng = pngRgba(simple);
  const complex = complexArt(1200, 800), complexPng = pngRgba(complex);

  write("images/simple.png", simplePng); rec("simple.png", "simple", opens("PNG", 320, 200), own);
  write("images/complex.png", complexPng); rec("complex.png", "complex", opens("PNG", 1200, 800), own, { notes: "Transparent corners must show the checkerboard." });
  write("images/simple.jpg", viaGdi(simplePng, "jpeg")); rec("simple.jpg", "simple", opens("JPEG", 320, 200), gdi);
  // EXIF orientation 6 (rotate 90° clockwise): shown portrait, 800 wide by 1200 high, as photo apps do.
  write("images/complex-rotated-exif.jpg", viaGdi(complexPng, "jpeg", [90, 6]));
  rec("complex-rotated-exif.jpg", "complex", opens("JPEG", 1200, 800), gdi, { notes: "EXIF orientation 6: must appear turned a quarter clockwise (portrait)." });
  write("images/simple.gif", viaGdi(simplePng, "gif")); rec("simple.gif", "simple", opens("GIF", 320, 200), gdi);
  write("images/simple.bmp", bmp(simple)); rec("simple.bmp", "simple", opens("BMP", 320, 200), own);
  write("images/simple.ico", ico(pngRgba(complexArt(256, 256)), 256)); rec("simple.ico", "simple", opens("icon", 256, 256), own);
  write("images/simple.webp", Buffer.from(await encodeWebp(simple, { quality: 80 }))); rec("simple.webp", "simple", opens("WebP", 320, 200), jsquash("webp"));
  write("images/complex.webp", Buffer.from(await encodeWebp(complex, { lossless: 1 }))); rec("complex.webp", "complex", opens("WebP", 1200, 800), jsquash("webp"), { notes: "Lossless with transparency." });
  write("images/simple.avif", Buffer.from(await encodeAvif(simple, { quality: 60, speed: 6 }))); rec("simple.avif", "simple", opens("AVIF", 0, 0), jsquash("avif"), { notes: "AVIF headers are not read; the page reports 320 × 200." });
  write("images/complex.avif", Buffer.from(await encodeAvif(complex, { quality: 70, speed: 6 }))); rec("complex.avif", "complex", opens("AVIF", 0, 0), jsquash("avif"), { notes: "With transparency; the page reports 1200 × 800." });

  write("images/simple.svg", `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="200" viewBox="0 0 400 200">
  <rect width="400" height="200" fill="#e8f0fe"/><circle cx="100" cy="100" r="60" fill="#1a73e8"/>
  <text x="190" y="110" font-family="Segoe UI, sans-serif" font-size="28" fill="#202124">Hello picture</text>
</svg>
`); rec("simple.svg", "simple", opens("SVG", 0, 0), "generator (SVG text)");
  write("images/complex.svg", `<?xml version="1.0" encoding="UTF-8"?>
<!-- Gradients, a clip path, a transform, and right-to-left and CJK text. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500">
  <defs>
    <linearGradient id="sky" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#1e3c72"/><stop offset="1" stop-color="#2a5298"/></linearGradient>
    <radialGradient id="sun"><stop offset="0" stop-color="#fff176"/><stop offset="1" stop-color="#f57f17"/></radialGradient>
    <clipPath id="frame"><rect x="20" y="20" width="760" height="460" rx="24"/></clipPath>
  </defs>
  <g clip-path="url(#frame)">
    <rect width="800" height="500" fill="url(#sky)"/>
    <circle cx="640" cy="130" r="70" fill="url(#sun)"/>
    <path d="M0 420 Q200 300 400 400 T800 380 V500 H0 Z" fill="#2e7d32"/>
    <g transform="rotate(-8 200 150)"><rect x="80" y="100" width="240" height="90" rx="12" fill="#ffffff" opacity="0.85"/></g>
  </g>
  <text x="400" y="250" font-family="Segoe UI, sans-serif" font-size="30" fill="#ffffff" text-anchor="middle">Hello picture</text>
  <text x="400" y="300" font-family="Segoe UI, Tahoma, sans-serif" font-size="26" fill="#ffffff" text-anchor="middle" direction="rtl">اردو: یہ ایک تصویر ہے · سنڌي · العربية</text>
  <text x="400" y="345" font-family="Microsoft YaHei, Yu Gothic, sans-serif" font-size="26" fill="#ffffff" text-anchor="middle">中文 · 日本語 · 한국어</text>
</svg>
`); rec("complex.svg", "complex", opens("SVG", 0, 0), "generator (SVG text)", { notes: "Right-to-left and CJK text, gradients, clip path." });

  // Hostile SVG: every way an SVG can try to run code or reach the network. Shown as a picture, none of it may happen.
  write("images/attack-svg-active.svg", `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="400" height="200" onload="fetch('${LISTENER}/svg-onload')">
  <script>new Image().src = "${LISTENER}/svg-script";</script>
  <style>@import url("${LISTENER}/svg-css-import"); .remote { fill: url("${LISTENER}/svg-css-fill#p"); } @font-face { font-family: Remote; src: url("${LISTENER}/svg-font"); }</style>
  <rect class="remote" width="400" height="200" fill="#fce8e6"/>
  <image href="${LISTENER}/svg-image.png" width="50" height="50"/>
  <image xlink:href="${WEBDAV_UNC}\\svg-unc.png" x="60" width="50" height="50"/>
  <image href="file://127.0.0.1@47831/share/svg-file.png" x="120" width="50" height="50"/>
  <use href="${LISTENER}/svg-use.svg#shape"/>
  <foreignObject width="200" height="50"><iframe xmlns="http://www.w3.org/1999/xhtml" src="${LISTENER}/svg-iframe"></iframe></foreignObject>
  <a href="javascript:fetch('${LISTENER}/svg-link')"><text x="20" y="150" font-family="Segoe UI" font-size="22" fill="#b3261e">Hostile SVG: nothing may load or run</text></a>
</svg>
`); rec("attack-svg-active.svg", "attack", opens("SVG", 0, 0), "generator (SVG text)", { notes: "Script, event handler, CSS import/font/fill, remote/UNC/file images, <use>, foreignObject iframe and a javascript: link. Zero listener requests allowed." });
  write("images/attack-svg-xxe.svg", `<?xml version="1.0"?>
<!DOCTYPE svg [<!ENTITY remote SYSTEM "${LISTENER}/svg-xxe/entity"><!ENTITY local SYSTEM "file:///C:/Windows/win.ini">]>
<svg xmlns="http://www.w3.org/2000/svg" width="400" height="100"><text x="10" y="50" font-size="20">External entities: &remote; &local;</text></svg>
`); rec("attack-svg-xxe.svg", "attack", opens("SVG", 0, 0), "generator (SVG text)",
    { notes: "Opens with the external entities left empty; they must never be fetched or read (zero listener requests)." });

  // Broken files.
  write("images/zero-byte.png", Buffer.alloc(0)); rec("zero-byte.png", "empty", { result: "error", error: "empty" }, "generator (empty file)");
  write("images/damaged-truncated.webp", fs.readFileSync(path.join(CORPUS, "images", "complex.webp")).subarray(0, 600));
  rec("damaged-truncated.webp", "damaged", { result: "open", format: "WebP", width: 1200, height: 800, incomplete: true }, `${jsquash("webp")}, then truncated`, { notes: "Shows what can be decoded, with a notice that the file is incomplete." });
  write("images/damaged-truncated.jpg", fs.readFileSync(path.join(CORPUS, "images", "complex-rotated-exif.jpg")).subarray(0, 60000));
  rec("damaged-truncated.jpg", "damaged", { result: "open", format: "JPEG", width: 1200, height: 800, incomplete: true }, `${gdi}, then truncated`);
  write("images/damaged-truncated.png", complexPng.subarray(0, Math.floor(complexPng.length / 2)));
  rec("damaged-truncated.png", "damaged", { result: "open", format: "PNG", width: 1200, height: 800, incomplete: true }, `${own}, then truncated`);
  write("images/damaged-header.png", Buffer.concat([simplePng.subarray(0, 8), Buffer.alloc(200)]));
  rec("damaged-header.png", "damaged", { result: "error", error: "damaged", stage: "renderer" }, `${own}, header overwritten`);
  write("images/not-a-picture.jpg", "Plain text saved with a .jpg name.\r\n"); rec("not-a-picture.jpg", "wrong-extension", { result: "error", error: "mismatch" }, "generator (text)");
  write("images/png-named.jpg", simplePng); rec("png-named.jpg", "wrong-extension", opens("PNG", 320, 200), own, { notes: "Identified by content: a PNG with a .jpg name opens as PNG." });
  write("images/tiff-named.png", viaGdi(simplePng, "tiff")); rec("tiff-named.png", "unsupported", { result: "error", error: "unsupported" }, gdi, { notes: "TIFF is planned for 0.3.0; until then a clear message." });
  // A valid PNG signature and header claiming 60,000 × 60,000 pixels: refused before any decoding.
  const bombHeader = Buffer.from(simplePng); bombHeader.writeUInt32BE(60000, 16); bombHeader.writeUInt32BE(60000, 20);
  write("images/attack-pixel-bomb.png", bombHeader); rec("attack-pixel-bomb.png", "attack", { result: "error", error: "too-large" }, `${own}, header dimensions changed`);

  if (large) {
    const target = (name, data) => { fs.mkdirSync(GENERATED, { recursive: true }); fs.writeFileSync(path.join(GENERATED, name), data); };
    const big = noise(8000, 6000), bigPng = pngRgba(big);
    target("image-large-8000x6000.png", bigPng);
    target("image-large-8000x6000.jpg", viaGdi(bigPng, "jpeg"));
    target("image-large-8000x6000.webp", Buffer.from(await encodeWebp(big, { quality: 80 })));
    target("image-large-4000x3000.avif", Buffer.from(await encodeAvif(noise(4000, 3000), { quality: 60, speed: 8 })));
    for (const [name, format, w, h] of [["image-large-8000x6000.png", "PNG", 8000, 6000], ["image-large-8000x6000.jpg", "JPEG", 8000, 6000],
      ["image-large-8000x6000.webp", "WebP", 8000, 6000], ["image-large-4000x3000.avif", "AVIF", 0, 0]])
      record({ id: `image-${name}`, file: `generated/${name}`, format: path.extname(name).slice(1), category: "large", generated: true, producer: name.endsWith(".png") ? own : name.endsWith(".jpg") ? gdi : jsquash(name.endsWith(".avif") ? "avif" : "webp"), licence, expect: opens(format, w, h), rules: SAFE_RULES });
  }
}
