import PDFDocument from "pdfkit";
import { write, record, streamToBuffer, chartPng, rawPdf, textStream, packageVersion, LISTENER, WEBDAV_UNC, SAFE_RULES, GENERATED, CORPUS } from "./lib.mjs";
import path from "node:path";
import fs from "node:fs";

const producer = `pdfkit ${packageVersion("pdfkit")} (Node)`;
const licence = "Generated by this repository; no third-party content";

function pdf(options = {}) {
  // A fixed date keeps regenerated files identical (except encrypted ones, which use a random key).
  const date = new Date(Date.UTC(2026, 8, 27));
  return new PDFDocument({ size: "A4", margin: 64, info: { Title: "Plain Viewer fixture", Producer: producer, CreationDate: date, ModDate: date }, ...options });
}

export async function generatePdf({ large }) {
  // Simple: one page of text.
  {
    const doc = pdf();
    doc.fontSize(20).text("Hello from Plain Viewer");
    doc.moveDown().fontSize(12).text("A one-page PDF with plain text, used to check that PDFs open, that search finds text, and that copying works.");
    write("pdf/simple.pdf", await streamToBuffer(doc));
    record({ id: "pdf-simple", file: "pdf/simple.pdf", format: "pdf", category: "simple", producer, licence,
      expect: { result: "open", pages: 1, text: ["Hello from Plain Viewer"] }, rules: SAFE_RULES });
  }

  // Complex: five pages, header and footer, table, image, outline, internal and external links.
  {
    const doc = pdf({ bufferPages: true });
    const image = chartPng();
    const sections = ["Overview", "Quarterly summary", "Regional table", "Chart", "Notes"];
    sections.forEach((title, i) => {
      if (i > 0) doc.addPage();
      doc.outline.addItem(title);
      doc.fontSize(22).fillColor("#1b3a5c").text(i === 0 ? "Hello complex PDF" : title);
      doc.moveDown(0.5).fontSize(11).fillColor("black");
      if (i === 0) {
        doc.text("This fixture has headers, footers, a table, an image, bookmarks and links. ");
        doc.fillColor("#0645ad").text("Go to the chart page", { goTo: "chart", underline: true });
        doc.fillColor("#0645ad").text("External link (must ask before opening)", { link: `${LISTENER}/pdf-complex/link`, underline: true });
        doc.fillColor("black");
      }
      if (title === "Quarterly summary") doc.text("Quarterly summary: revenue rose 12.5% while costs fell. ".repeat(12));
      if (title === "Regional table") {
        const rows = [["Region", "Q1", "Q2", "Q3"], ["North", "1,200", "1,350", "1,410"], ["South", "980", "1,020", "1,105"], ["Sindh", "1,540", "1,610", "1,700"]];
        let y = doc.y + 8;
        rows.forEach((row, r) => {
          row.forEach((cell, c) => {
            doc.rect(64 + c * 110, y, 110, 24).stroke("#888888");
            doc.fillColor("black").font(r === 0 ? "Helvetica-Bold" : "Helvetica").text(cell, 70 + c * 110, y + 7, { width: 100 });
          });
          y += 24;
        });
        doc.font("Helvetica").text("", 64, y + 12);
      }
      if (title === "Chart") { doc.addNamedDestination("chart"); doc.image(image, { width: 360 }); doc.moveDown().text("Figure 1: bars drawn as an embedded PNG image."); }
      if (title === "Notes") doc.text("Last page. Search for 'Sindh' should find two matches: one in the table and this one.");
    });
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc.fontSize(9).fillColor("#555555");
      doc.text("Plain Viewer test corpus — confidential header", 64, 30, { lineBreak: false });
      doc.text(`Page ${i + 1} of ${range.count}`, 64, doc.page.height - 40, { lineBreak: false });
    }
    write("pdf/complex.pdf", await streamToBuffer(doc));
    record({ id: "pdf-complex", file: "pdf/complex.pdf", format: "pdf", category: "complex", producer, licence,
      expect: { result: "open", pages: 5, text: ["Hello complex PDF", "Quarterly summary", "Sindh"], searchCounts: { Sindh: 2 } },
      rules: { ...SAFE_RULES, links: `${LISTENER}/pdf-complex/link must only open after confirmation` } });
  }

  // Password protected (AES-256). The password is a published test value, not a secret.
  {
    const doc = pdf({ userPassword: "viewer-test", ownerPassword: "viewer-owner", pdfVersion: "1.7ext3" });
    doc.fontSize(20).text("Hello secret PDF");
    write("pdf/password.pdf", await streamToBuffer(doc));
    record({ id: "pdf-password", file: "pdf/password.pdf", format: "pdf", category: "password", producer, licence, password: "viewer-test",
      expect: { result: "password", afterPassword: { pages: 1, text: ["Hello secret PDF"] } }, rules: SAFE_RULES });
  }

  // Damaged: the complex file cut to 35% of its length.
  {
    const full = fs.readFileSync(path.join(CORPUS, "pdf", "complex.pdf"));
    write("pdf/damaged-truncated.pdf", full.subarray(0, Math.floor(full.length * 0.35)));
    record({ id: "pdf-truncated", file: "pdf/damaged-truncated.pdf", format: "pdf", category: "damaged", producer: `${producer}, then truncated`, licence,
      expect: { result: "error", error: "damaged" }, rules: SAFE_RULES,
      notes: "Some readers can recover early pages from a truncated file; either a clear damaged-file message or a partial view without a crash is acceptable." });
  }

  write("pdf/zero-byte.pdf", Buffer.alloc(0));
  record({ id: "pdf-zero-byte", file: "pdf/zero-byte.pdf", format: "pdf", category: "empty", producer: "generator (empty file)", licence,
    expect: { result: "error", error: "empty" }, rules: SAFE_RULES });

  write("pdf/not-a-pdf.pdf", "This is plain text saved with a .pdf name.\r\n");
  record({ id: "pdf-mismatch", file: "pdf/not-a-pdf.pdf", format: "pdf", category: "wrong-extension", producer: "generator (text)", licence,
    expect: { result: "error", error: "mismatch" }, rules: SAFE_RULES });

  // Hostile: JavaScript that runs on open and tries to reach the listener.
  write("pdf/attack-javascript.pdf", rawPdf([
    `<< /Type /Catalog /Pages 2 0 R /OpenAction 5 0 R /Names << /JavaScript << /Names [(boot) 5 0 R] >> >> >>`,
    `<< /Type /Pages /Kids [3 0 R] /Count 1 >>`,
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 6 0 R >> >> /Contents 4 0 R /AA << /O 5 0 R >> >>`,
    textStream(["Hello script test", "This PDF asks the viewer to run JavaScript when it opens.", "A safe viewer shows this text and runs nothing."]),
    `<< /S /JavaScript /JS (app.launchURL\\("${LISTENER}/pdf-javascript/openaction", true\\); this.submitForm\\("${LISTENER}/pdf-javascript/submit"\\);) >>`,
    `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`
  ]));
  record({ id: "attack-pdf-javascript", file: "pdf/attack-javascript.pdf", format: "pdf", category: "attack", producer: "hand-written PDF (generator)", licence,
    expect: { result: "open", pages: 1, text: ["Hello script test"] }, rules: SAFE_RULES,
    notes: "OpenAction and page-open JavaScript call the listener. Any request under /pdf-javascript/ is a failure." });

  // Hostile: links that launch a program, reach a network share, or use file: URLs.
  const link = (rect, action) => `<< /Type /Annot /Subtype /Link /Rect [${rect}] /Border [0 0 1] /A ${action} >>`;
  write("pdf/attack-links.pdf", rawPdf([
    `<< /Type /Catalog /Pages 2 0 R >>`,
    `<< /Type /Pages /Kids [3 0 R] /Count 1 >>`,
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R /Annots [6 0 R 7 0 R 8 0 R 9 0 R] >>`,
    textStream(["Hello link test", "1. Launch calc.exe (must never run)", "2. Network share by UNC path (must not open)", "3. file: URL to another machine (must not open)", "4. Web address (may open only after confirmation)"]),
    `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`,
    link("72 716 400 732", `<< /S /Launch /F (C:\\\\Windows\\\\System32\\\\calc.exe) /Win << /F (calc.exe) >> >>`),
    link("72 698 400 714", `<< /S /URI /URI (${WEBDAV_UNC.replace(/\\/g, "\\\\")}\\\\pdf-unc.txt) >>`),
    link("72 680 400 696", `<< /S /URI /URI (file://127.0.0.1@47831/share/pdf-file-url.txt) >>`),
    link("72 662 400 678", `<< /S /URI /URI (${LISTENER}/pdf-links/web) >>`)
  ]));
  record({ id: "attack-pdf-links", file: "pdf/attack-links.pdf", format: "pdf", category: "attack", producer: "hand-written PDF (generator)", licence,
    expect: { result: "open", pages: 1, text: ["Hello link test"] }, rules: { ...SAFE_RULES, links: "Only the web address may open, and only after confirmation. Nothing is contacted while opening or scrolling." },
    notes: "Manual check: click each link. Automated check: opening makes no request to the listener." });

  if (large) {
    const doc = pdf();
    for (let i = 1; i <= 500; i++) {
      if (i > 1) doc.addPage();
      doc.fontSize(18).text(`Large PDF page ${i}`);
      doc.fontSize(10).text(`Hello page ${i}. `.repeat(180));
    }
    fs.mkdirSync(GENERATED, { recursive: true });
    write("generated/pdf-large-500-pages.pdf", await streamToBuffer(doc));
    record({ id: "pdf-large", file: "generated/pdf-large-500-pages.pdf", format: "pdf", category: "large", producer, licence, generated: true,
      expect: { result: "open", pages: 500, text: ["Large PDF page 500"] }, rules: SAFE_RULES });
  }
}
