import PptxGenJS from "pptxgenjs";
import { write, record, packageVersion, stableZip, officeVariants, chartPng, LISTENER, SAFE_RULES } from "./lib.mjs";

const producer = `pptxgenjs ${packageVersion("pptxgenjs")} (Node)`;
const licence = "Generated by this repository; no third-party content";

function deck() {
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_16x9";
  pptx.author = "Plain Viewer corpus"; pptx.company = "Plain Viewer"; pptx.title = "Plain Viewer fixture";
  return pptx;
}
const pack = async pptx => stableZip(await pptx.write({ outputType: "nodebuffer" }));

export async function generatePptx() {
  // Simple: three slides.
  const simpleDeck = deck();
  ["Hello slides", "Second slide", "Third slide"].forEach((title, i) => {
    const slide = simpleDeck.addSlide();
    slide.addText(title, { x: 0.6, y: 0.5, w: 8.8, h: 1, fontSize: 36, bold: i === 0 });
    slide.addText(`Slide ${i + 1} body text.`, { x: 0.6, y: 1.8, w: 8.8, h: 1, fontSize: 20 });
  });
  const simple = await pack(simpleDeck);
  write("pptx/simple.pptx", simple);
  record({ id: "pptx-simple", file: "pptx/simple.pptx", format: "pptx", category: "simple", producer, licence,
    expect: { result: "open", slides: 3, text: ["Hello slides"] }, rules: SAFE_RULES });

  // Complex: twelve slides covering text, bullets, table, chart, image, shapes, notes, RTL and CJK text, links.
  const pptx = deck();
  const image = "image/png;base64," + chartPng().toString("base64");
  const titled = (title, notes) => { const s = pptx.addSlide(); s.addText(title, { x: 0.5, y: 0.3, w: 9, h: 0.8, fontSize: 30, bold: true, color: "1B3A5C" }); s.slideNumber = { x: 9.2, y: 5.2, fontSize: 10 }; if (notes) s.addNotes(notes); return s; };
  titled("Hello complex presentation", "Speaker notes for the title slide.").addText("Twelve slides of test content", { x: 0.5, y: 1.4, w: 9, h: 0.6, fontSize: 20 });
  titled("Bullets").addText([{ text: "First point", options: { bullet: true } }, { text: "Second point", options: { bullet: true } }, { text: "Indented point", options: { bullet: { indent: 30 }, indentLevel: 1 } }], { x: 0.7, y: 1.3, w: 8.5, h: 3, fontSize: 20 });
  titled("Table").addTable([["Region", "Q1", "Q2"], ["North", "1,200", "1,350"], ["Sindh", "1,540", "1,610"]].map((r, i) => r.map(t => ({ text: t, options: { bold: i === 0 } }))), { x: 0.7, y: 1.4, w: 8, colW: [3, 2.5, 2.5], fontSize: 16, border: { type: "solid", color: "888888", pt: 1 } });
  titled("Chart").addChart(pptx.ChartType.bar, [{ name: "Sales", labels: ["North", "South", "East", "Sindh"], values: [12, 9, 7, 15] }], { x: 0.7, y: 1.3, w: 8.5, h: 3.8, showLegend: false, showValue: true });
  titled("Image").addImage({ data: image, x: 2.5, y: 1.4, w: 4.8, h: 2.4, altText: "Four coloured bars" });
  const shapes = titled("Shapes");
  shapes.addShape(pptx.ShapeType.rect, { x: 0.8, y: 1.5, w: 2.4, h: 1.4, fill: { color: "266DB3" } });
  shapes.addShape(pptx.ShapeType.ellipse, { x: 3.7, y: 1.5, w: 2.4, h: 1.4, fill: { color: "2E9E6B" } });
  shapes.addShape(pptx.ShapeType.rightArrow, { x: 6.6, y: 1.7, w: 2.4, h: 1, fill: { color: "D98C1F" } });
  titled("Right to left", "Notes: Urdu, Sindhi and Arabic text.").addText("اردو: یہ ایک دستاویز ہے\nسنڌي: سلام دنيا\nالعربية: مرحبا بالعالم", { x: 0.7, y: 1.3, w: 8.5, h: 2.5, fontSize: 24, rtlMode: true, align: "right" });
  titled("Chinese and Japanese").addText("中文：你好世界\n日本語：こんにちは", { x: 0.7, y: 1.3, w: 8.5, h: 2, fontSize: 28 });
  titled("Link").addText([{ text: "External link (must ask before opening)", options: { hyperlink: { url: `${LISTENER}/pptx-complex/link` } } }], { x: 0.7, y: 1.5, w: 8.5, h: 0.8, fontSize: 20 });
  titled("Long text").addText("Quarterly summary: revenue rose 12.5% while costs fell. ".repeat(8), { x: 0.7, y: 1.3, w: 8.5, h: 3.5, fontSize: 14, valign: "top" });
  titled("Animation note").addText("This slide would animate in PowerPoint; the viewer shows it as a static slide.", { x: 0.7, y: 1.4, w: 8.5, h: 1, fontSize: 18 });
  titled("Last slide").addText("End of the test presentation.", { x: 0.7, y: 1.4, w: 8.5, h: 1, fontSize: 18 });
  const complex = await pack(pptx);
  write("pptx/complex.pptx", complex);
  record({ id: "pptx-complex", file: "pptx/complex.pptx", format: "pptx", category: "complex", producer, licence,
    expect: { result: "open", slides: 12, text: ["Hello complex presentation", "Sindh", "سنڌي"] },
    rules: { ...SAFE_RULES, links: `${LISTENER}/pptx-complex/link must only open after confirmation` } });

  // Empty: one blank slide.
  const empty = deck(); empty.addSlide();
  write("pptx/empty.pptx", await pack(empty));
  record({ id: "pptx-empty", file: "pptx/empty.pptx", format: "pptx", category: "empty", producer, licence, expect: { result: "open", slides: 1 }, rules: SAFE_RULES });

  // Hostile: a picture linked (not embedded) to the listener.
  write("pptx/attack-remote-image.pptx", await stableZip(simple, async zip => {
    const slide = await zip.file("ppt/slides/slide1.xml").async("string");
    const pic = `<p:pic><p:nvPicPr><p:cNvPr id="900" name="Remote picture"/><p:cNvPicPr/><p:nvPr/></p:nvPicPr><p:blipFill><a:blip r:link="rIdRemote1"/><a:stretch><a:fillRect/></a:stretch></p:blipFill><p:spPr><a:xfrm><a:off x="6000000" y="3000000"/><a:ext cx="1500000" cy="1000000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr></p:pic>`;
    zip.file("ppt/slides/slide1.xml", slide.replace("</p:spTree>", pic + "</p:spTree>"));
    const rels = await zip.file("ppt/slides/_rels/slide1.xml.rels").async("string");
    zip.file("ppt/slides/_rels/slide1.xml.rels", rels.replace("</Relationships>", `<Relationship Id="rIdRemote1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="${LISTENER}/pptx-remote-image/picture.png" TargetMode="External"/></Relationships>`));
  }));
  record({ id: "attack-pptx-remote-image", file: "pptx/attack-remote-image.pptx", format: "pptx", category: "attack", producer: `${producer}, edited with JSZip`, licence,
    expect: { result: "open", slides: 3, text: ["Hello slides"] }, rules: SAFE_RULES, notes: "Any request under /pptx-remote-image/ is a failure." });

  await officeVariants({ format: "pptx", folder: "pptx", simple, complex, mainPart: "ppt/presentation.xml", textPart: "ppt/slides/slide1.xml",
    macroType: "application/vnd.ms-powerpoint.presentation.macroEnabled.main+xml", macroExtension: "pptm", producer, licence });
}
