import ExcelJS from "exceljs";
import JSZip from "jszip";
import officeCrypto from "officecrypto-tool";
import CFB from "cfb";
import fs from "node:fs";
import path from "node:path";
import { write, record, packageVersion, chartPng, LISTENER, WEBDAV_UNC, SAFE_RULES, CORPUS } from "./lib.mjs";

const producer = `exceljs ${packageVersion("exceljs")} (Node)`;
const licence = "Generated by this repository; no third-party content";
const date = new Date(Date.UTC(2026, 8, 27));

function workbook() {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Plain Viewer corpus"; wb.created = date; wb.modified = date;
  return wb;
}

// ZIP output from exceljs embeds the current time in entry headers; rewrite entries with a fixed date so
// regenerated fixtures are identical.
async function stable(buffer) {
  const zip = await JSZip.loadAsync(buffer);
  zip.forEach((_, file) => { file.date = date; });
  return zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE", compressionOptions: { level: 6 } });
}

// Cell styles: fonts, fills (direct and theme colours with tint), borders, alignment, indent, wrap, text that spills
// over empty neighbours, a styled empty cell and a hidden column.
function stylesWorkbook() {
  const wb = workbook();
  const ws = wb.addWorksheet("Styles");
  ws.columns = [{ width: 14 }, { width: 14 }, { width: 14 }, { width: 14 }, { width: 14, hidden: true }, { width: 14 }];
  const set = (ref, value, style) => { const cell = ws.getCell(ref); cell.value = value; Object.assign(cell, style); };
  set("A1", "Bold red", { font: { bold: true, color: { argb: "FFC00000" } } });
  set("B1", "Italic", { font: { italic: true } });
  set("C1", "Underlined", { font: { underline: true } });
  set("D1", "Struck", { font: { strike: true } });
  set("A2", "Yellow fill", { fill: { type: "pattern", pattern: "solid", fgColor: { argb: "FFFFFF00" } } });
  set("B2", "Theme fill", { fill: { type: "pattern", pattern: "solid", fgColor: { theme: 4, tint: 0.3999755851924192 } } });
  set("C2", null, { fill: { type: "pattern", pattern: "solid", fgColor: { argb: "FF00B050" } } });
  set("A3", "Boxed", { border: { top: { style: "thin", color: { argb: "FF0000FF" } }, bottom: { style: "double", color: { argb: "FF0000FF" } },
    left: { style: "medium" }, right: { style: "dashed", color: { argb: "FFFF0000" } } } });
  set("B3", "Centred", { alignment: { horizontal: "center" } });
  set("C3", "Right", { alignment: { horizontal: "right" } });
  set("D3", 1234.5, { alignment: { horizontal: "left" }, numFmt: "#,##0.00" });
  set("A4", "Indented", { alignment: { indent: 2 } });
  set("B4", "Big text", { font: { size: 16 } });
  set("C4", "Consolas", { font: { name: "Consolas" } });
  set("D4", "Wrapped text that is long", { alignment: { wrapText: true, vertical: "top" } });
  // Spill: A5 runs over the empty B5:D5; A6 cannot, because B6 has content.
  set("A5", "Hello spill: this text is longer than its column and runs over the empty cells beside it", {});
  set("A6", "No room to spill here", {}); set("B6", "Neighbour", {});
  set("F1", "After hidden E", {});
  ws.getRow(4).height = 45;                                  // tall enough for D4's wrapped text
  // Whole column G and whole row 8 filled: Excel saves no cells for their empty part (the row's fill wins in G8).
  ws.getColumn(7).width = 10;
  ws.getColumn(7).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFDDEBF7" } };
  ws.getRow(8).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFFCE4D6" } };
  ws.getCell("A8").value = "Filled row";
  return wb;
}

// A chart part: one chart of the given kind with cached categories and values, and references to the cells they came
// from (series in columns B, C, ... of rows 2-5 by default; a pie chart of one row passes `across`; other workbooks
// pass `refs` with their own name(i), cat and val(i) references, and `stacked` for a stacked column chart).
export function chartXml({ kind, title, categories, series, across, refs, stacked }) {
  const strCache = values => `<c:strCache><c:ptCount val="${values.length}"/>${values.map((v, i) => `<c:pt idx="${i}"><c:v>${v}</c:v></c:pt>`).join("")}</c:strCache>`;
  const numCache = values => `<c:numCache><c:formatCode>General</c:formatCode><c:ptCount val="${values.length}"/>${values.map((v, i) => `<c:pt idx="${i}"><c:v>${v}</c:v></c:pt>`).join("")}</c:numCache>`;
  const nameRef = i => refs ? refs.name(i) : `Sales!$${"BC"[i] ?? "B"}$1`;
  const catRef = refs ? refs.cat : across ? across.cat : "Sales!$A$2:$A$5";
  const valRef = i => refs ? refs.val(i) : across ? across.val : `Sales!$${"BC"[i] ?? "B"}$2:$${"BC"[i] ?? "B"}$5`;
  const ser = series.map(([name, values, colour], i) => `<c:ser><c:idx val="${i}"/><c:order val="${i}"/><c:tx><c:strRef><c:f>${nameRef(i)}</c:f>${strCache([name])}</c:strRef></c:tx>` +
    (colour ? `<c:spPr><a:solidFill><a:srgbClr val="${colour}"/></a:solidFill></c:spPr>` : "") +
    `<c:cat><c:strRef><c:f>${catRef}</c:f>${strCache(categories)}</c:strRef></c:cat>` +
    `<c:val><c:numRef><c:f>${valRef(i)}</c:f>${numCache(values)}</c:numRef></c:val></c:ser>`).join("");
  const round = kind === "pieChart" || kind === "doughnutChart";
  const axes = round ? "" : '<c:axId val="1"/><c:axId val="2"/>';
  const body = kind === "barChart" ? `<c:barChart><c:barDir val="col"/><c:grouping val="${stacked ? "stacked" : "clustered"}"/><c:varyColors val="0"/>${ser}${stacked ? '<c:overlap val="100"/>' : ""}${axes}</c:barChart>`
    : kind === "lineChart" ? `<c:lineChart><c:grouping val="standard"/><c:varyColors val="0"/>${ser}<c:marker val="1"/>${axes}</c:lineChart>`
    : kind === "doughnutChart" ? `<c:doughnutChart><c:varyColors val="1"/>${ser}<c:firstSliceAng val="0"/><c:holeSize val="50"/></c:doughnutChart>`
    : `<c:pieChart><c:varyColors val="1"/>${ser}<c:firstSliceAng val="0"/></c:pieChart>`;
  const axisParts = round ? "" : '<c:catAx><c:axId val="1"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:delete val="0"/><c:axPos val="b"/><c:crossAx val="2"/></c:catAx>' +
    '<c:valAx><c:axId val="2"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:delete val="0"/><c:axPos val="l"/><c:majorGridlines/><c:crossAx val="1"/></c:valAx>';
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">` +
    `<c:chart><c:title><c:tx><c:rich><a:bodyPr/><a:p><a:r><a:t>${title}</a:t></a:r></a:p></c:rich></c:tx><c:overlay val="0"/></c:title><c:autoTitleDeleted val="0"/><c:plotArea><c:layout/>${body}${axisParts}</c:plotArea>` +
    `<c:legend><c:legendPos val="b"/><c:overlay val="0"/></c:legend><c:plotVisOnly val="1"/></c:chart></c:chartSpace>`;
}

export async function generateXlsx({ large }) {
  {
    write("xlsx/styles.xlsx", await stable(await stylesWorkbook().xlsx.writeBuffer()));
    record({ id: "xlsx-styles", file: "xlsx/styles.xlsx", format: "xlsx", category: "complex", producer, licence,
      expect: { result: "open", sheets: ["Styles"],
        cells: [{ sheet: "Styles", ref: "D3", text: "1,234.50" }, { sheet: "Styles", ref: "A5", text: "Hello spill: this text is longer than its column and runs over the empty cells beside it" }],
        styles: [
          { ref: "A1", bold: true, color: "#c00000" }, { ref: "B1", italic: true }, { ref: "C1", underline: true }, { ref: "D1", strike: true },
          { ref: "A2", fill: "#ffff00" }, { ref: "B2", fill: "#95b3d7" }, { ref: "C2", fill: "#00b050" },
          { ref: "A3", top: "1 solid #0000ff", bottom: "3 double #0000ff", left: "2 solid #000000", right: "1 dashed #ff0000" },
          { ref: "A4", indent: 2 }, { ref: "B4", size: 1.455 }, { ref: "C4", font: "Consolas" }, { ref: "D4", wrap: true, vAlign: "top" },
          { ref: "G2", fill: "#ddebf7" }, { ref: "G6", fill: "#ddebf7" }, { ref: "B8", fill: "#fce4d6" }, { ref: "G8", fill: "#fce4d6" }, { ref: "B7", fill: null }],
        align: [{ ref: "B3", align: "c" }, { ref: "C3", align: "r" }, { ref: "D3", align: "l" }],
        hiddenColumns: ["E"], defaultRowHeight: 15, rowHeights: [{ row: 4, points: 45 }] },
      rules: SAFE_RULES, notes: "Theme fill: accent1 of the Office 2007 theme exceljs writes (#4f81bd) lightened by 40% is #95b3d7, as Excel shows it. Wrapped text shows its first line (row heights are not applied). A5 must spill over B5:D5; A6 must not." });
  }
  // Conditional formatting, worked out from saved values; the expression rule needs a formula and is not shown.
  {
    const wb = workbook();
    const ws = wb.addWorksheet("Rules");
    ws.getRow(1).values = ["Hello: over 35", "Colour scale", "Data bar", "Icons", "Text", "Formula rule"];
    const words = ["apple pie", "banana", "pineapple", "cherry", "grape", "melon"];
    for (let i = 0; i < 6; i++) ws.getRow(i + 2).values = [10 * (i + 1), 10 * (i + 1), 10 * (i + 1), 10 * (i + 1), words[i], i];
    const fill = argb => ({ type: "pattern", pattern: "solid", bgColor: { argb } });
    ws.addConditionalFormatting({ ref: "A2:A7", rules: [{ type: "cellIs", operator: "greaterThan", formulae: [35], priority: 1,
      style: { fill: fill("FFFFC7CE"), font: { color: { argb: "FF9C0006" } } } }] });
    ws.addConditionalFormatting({ ref: "B2:B7", rules: [{ type: "colorScale", priority: 2, cfvo: [{ type: "min" }, { type: "max" }],
      color: [{ argb: "FFF8696B" }, { argb: "FF63BE7B" }] }] });
    ws.addConditionalFormatting({ ref: "C2:C7", rules: [{ type: "dataBar", priority: 3, minLength: 0, maxLength: 100,
      cfvo: [{ type: "min" }, { type: "max" }], color: { argb: "FF638EC6" } }] });
    ws.addConditionalFormatting({ ref: "D2:D7", rules: [{ type: "iconSet", iconSet: "3Arrows", priority: 4,
      cfvo: [{ type: "percent", value: 0 }, { type: "percent", value: 33 }, { type: "percent", value: 67 }] }] });
    ws.addConditionalFormatting({ ref: "E2:E7", rules: [{ type: "containsText", operator: "containsText", text: "apple", priority: 5,
      style: { font: { italic: true } } }] });
    ws.addConditionalFormatting({ ref: "F2:F7", rules: [{ type: "expression", formulae: ["F2>2"], priority: 6, style: { fill: fill("FFFFEB9C") } }] });
    // exceljs leaves out the text attribute that Excel writes on text rules; add it as Excel does. The data bar's id
    // (random in exceljs) is fixed so the file is the same every time.
    const zip = await JSZip.loadAsync(await wb.xlsx.writeBuffer());
    const sheetXml = await zip.file("xl/worksheets/sheet1.xml").async("string");
    zip.file("xl/worksheets/sheet1.xml", sheetXml.replace('type="containsText" dxfId="1"', 'type="containsText" dxfId="1" operator="containsText" text="apple"')
      .replace(/\{[0-9A-Fa-f-]{36}\}/g, "{00000000-0000-4000-8000-000000000001}"));
    write("xlsx/conditional.xlsx", await stable(await zip.generateAsync({ type: "nodebuffer" })));
    record({ id: "xlsx-conditional", file: "xlsx/conditional.xlsx", format: "xlsx", category: "complex", producer, licence,
      expect: { result: "open", sheets: ["Rules"], cells: [{ sheet: "Rules", ref: "A5", text: "40" }, { sheet: "Rules", ref: "E2", text: "apple pie" }],
        styles: [
          { ref: "A2", fill: null }, { ref: "A5", fill: "#ffc7ce", color: "#9c0006" },
          { ref: "B2", fill: "#f8696b" }, { ref: "B3", fill: "#da7a6e" }, { ref: "B7", fill: "#63be7b" },
          { ref: "C2", bar: "0 #638ec6" }, { ref: "C7", bar: "100 #638ec6" },
          { ref: "D2", icon: "arrow-down red" }, { ref: "D4", icon: "arrow-right yellow" }, { ref: "D7", icon: "arrow-up green" },
          { ref: "E2", italic: true }, { ref: "E3", italic: null }, { ref: "E4", italic: true },
          { ref: "F7", fill: null }],
        workbookNotice: "1 conditional formatting rule is not shown" },
      rules: SAFE_RULES, notes: "Rules applied to saved values: cell value, colour scale, data bar, icon set, text contains. The formula (expression) rule is counted in the notice and not shown." });
  }
  // Simple
  {
    const wb = workbook();
    const ws = wb.addWorksheet("Hello");
    ws.getCell("A1").value = "Hello spreadsheet";
    ws.getCell("B1").value = 42;
    ws.getCell("A2").value = "Second row";
    ws.getCell("B2").value = 3.14;
    write("xlsx/simple.xlsx", await stable(await wb.xlsx.writeBuffer()));
    record({ id: "xlsx-simple", file: "xlsx/simple.xlsx", format: "xlsx", category: "simple", producer, licence,
      expect: { result: "open", sheets: ["Hello"], text: ["Hello spreadsheet"], cells: [{ sheet: "Hello", ref: "B1", text: "42" }, { sheet: "Hello", ref: "B2", text: "3.14" }] },
      rules: SAFE_RULES });
  }

  // Complex: formats, merge, frozen panes, widths, cached and missing formula results, RTL, hidden sheets.
  {
    const wb = workbook();
    const ws = wb.addWorksheet("Summary", { views: [{ state: "frozen", xSplit: 1, ySplit: 2 }] });
    ws.columns = [{ width: 16 }, { width: 14 }, { width: 10 }, { width: 12 }, { width: 8 }, { width: 12 }];
    ws.mergeCells("A1:D1");
    ws.getCell("A1").value = "Hello workbook summary";
    ws.getRow(2).values = ["Item", "Amount", "Share", "Date", "Time", "Code"];
    const money = '"$"#,##0.00;[Red]-"$"#,##0.00';
    const rows = [["Alpha", 10, 0.1, Date.UTC(2026, 8, 27), 0.5, "00123"], ["Beta", 20, 0.2, Date.UTC(2026, 0, 15), 0.75, "00456"],
      ["Gamma", 30, 0.3, Date.UTC(2025, 11, 31), 0.25, "Hello cell"], ["Delta", -40, 0.4, Date.UTC(2024, 1, 29), 0, "=1+1"]];
    rows.forEach((values, i) => {
      const r = 3 + i;
      ws.getCell(`A${r}`).value = values[0];
      ws.getCell(`B${r}`).value = values[1]; ws.getCell(`B${r}`).numFmt = money;
      ws.getCell(`C${r}`).value = values[2]; ws.getCell(`C${r}`).numFmt = "0.0%";
      ws.getCell(`D${r}`).value = new Date(values[3]); ws.getCell(`D${r}`).numFmt = "yyyy-mm-dd";
      ws.getCell(`E${r}`).value = values[4]; ws.getCell(`E${r}`).numFmt = "hh:mm";
      ws.getCell(`F${r}`).value = values[5];                        // text, including leading zeros and "=1+1"
    });
    ws.getCell("A7").value = "Total";
    ws.getCell("B7").value = { formula: "SUM(B3:B6)", result: 20 }; ws.getCell("B7").numFmt = money;
    ws.getCell("A8").value = "Missing";
    ws.getCell("B8").value = { formula: "B3*2" };                     // no cached result on purpose
    ws.getCell("A9").value = "Web service";
    ws.getCell("B9").value = { formula: `WEBSERVICE("${LISTENER}/xlsx-webservice")`, result: "cached-ok" };
    ws.getCell("A10").value = "External";
    ws.getCell("B10").value = { formula: `'[${WEBDAV_UNC}\\book.xlsx]Sheet1'!A1`, result: 7 };
    ws.getCell("A11").value = "Flags";
    ws.getCell("B11").value = true;
    ws.getCell("C11").value = { error: "#DIV/0!" };
    ws.getCell("A12").value = "Big";
    ws.getCell("B12").value = 1234567.891; ws.getCell("B12").numFmt = "#,##0.00";
    ws.getCell("A13").value = "General";
    ws.getCell("B13").value = 0.1 + 0.2;

    const rtl = wb.addWorksheet("Urdu", { views: [{ rightToLeft: true }] });
    rtl.columns = [{ width: 36 }];
    ["اردو: یہ ایک دستاویز ہے", "سنڌي: سلام دنيا", "العربية: مرحبا بالعالم", "中文：你好世界", "日本語：こんにちは"].forEach((t, i) => { rtl.getCell(`A${i + 1}`).value = t; });

    wb.addWorksheet("HiddenData", { state: "hidden" }).getCell("A1").value = "Secret hidden value";
    wb.addWorksheet("VeryHidden", { state: "veryHidden" }).getCell("A1").value = "Very hidden value";
    write("xlsx/complex.xlsx", await stable(await wb.xlsx.writeBuffer()));
    const cell = (ref, text) => ({ sheet: "Summary", ref, text });
    record({ id: "xlsx-complex", file: "xlsx/complex.xlsx", format: "xlsx", category: "complex", producer, licence,
      expect: {
        result: "open", sheets: ["Summary", "Urdu"], hiddenSheetsNotShown: ["HiddenData", "VeryHidden"], culture: "en-US",
        text: ["Hello workbook summary", "Hello cell"],
        cells: [cell("A1", "Hello workbook summary"), cell("B3", "$10.00"), cell("C3", "10.0%"), cell("D3", "2026-09-27"), cell("E3", "12:00"),
          cell("F3", "00123"), cell("F6", "=1+1"), cell("B6", "-$40.00"), cell("B7", "$20.00"), cell("B8", "Result unavailable"),
          cell("B9", "cached-ok"), cell("B10", "7"), cell("B11", "TRUE"), cell("C11", "#DIV/0!"), cell("B12", "1,234,567.89"), cell("B13", "0.3"),
          { sheet: "Urdu", ref: "A2", text: "سنڌي: سلام دنيا" }],
        merges: [{ sheet: "Summary", range: "A1:D1" }], frozen: { sheet: "Summary", rows: 2, columns: 1 }, rightToLeft: ["Urdu"]
      },
      rules: { ...SAFE_RULES, formulas: "Never recalculated; WEBSERVICE and the external workbook reference must not be contacted" } });
  }

  // Empty worksheet
  {
    const wb = workbook(); wb.addWorksheet("Blank");
    write("xlsx/empty-sheet.xlsx", await stable(await wb.xlsx.writeBuffer()));
    record({ id: "xlsx-empty-sheet", file: "xlsx/empty-sheet.xlsx", format: "xlsx", category: "empty", producer, licence,
      expect: { result: "open", sheets: ["Blank"], notice: "This sheet is empty." }, rules: SAFE_RULES });
  }

  // Password protected (Agile encryption). Test password, not a secret.
  {
    const plain = fs.readFileSync(path.join(CORPUS, "xlsx", "simple.xlsx"));
    write("xlsx/password.xlsx", officeCrypto.encrypt(plain, { password: "viewer-test" }));
    record({ id: "xlsx-password", file: "xlsx/password.xlsx", format: "xlsx", category: "password",
      producer: `${producer}, encrypted with officecrypto-tool ${packageVersion("officecrypto-tool")}`, licence, password: "viewer-test",
      expect: { result: "error", error: "password" }, rules: SAFE_RULES,
      notes: "v1 only needs a clear explanation for protected Office files; entering a password is not required." });
  }

  // An older binary container (not encrypted) saved with an .xlsx name.
  {
    const container = CFB.utils.cfb_new();
    CFB.utils.cfb_add(container, "Workbook", Buffer.from("Not a real BIFF stream; container only."));
    write("xlsx/old-format-renamed.xlsx", Buffer.from(CFB.write(container, { type: "buffer" })));
    record({ id: "xlsx-old-format", file: "xlsx/old-format-renamed.xlsx", format: "xlsx", category: "wrong-extension", producer: `cfb ${packageVersion("cfb")} (Node)`, licence,
      expect: { result: "error", error: "mismatch" }, rules: SAFE_RULES });
  }

  // Damaged, empty and mislabelled files
  {
    const full = fs.readFileSync(path.join(CORPUS, "xlsx", "complex.xlsx"));
    write("xlsx/damaged-truncated.xlsx", full.subarray(0, Math.floor(full.length * 0.5)));
    record({ id: "xlsx-truncated", file: "xlsx/damaged-truncated.xlsx", format: "xlsx", category: "damaged", producer: `${producer}, then truncated`, licence,
      expect: { result: "error", error: "damaged" }, rules: SAFE_RULES });
    write("xlsx/zero-byte.xlsx", Buffer.alloc(0));
    record({ id: "xlsx-zero-byte", file: "xlsx/zero-byte.xlsx", format: "xlsx", category: "empty", producer: "generator (empty file)", licence,
      expect: { result: "error", error: "empty" }, rules: SAFE_RULES });
    write("xlsx/not-a-workbook.xlsx", "Plain text saved with an .xlsx name.\r\n");
    record({ id: "xlsx-mismatch", file: "xlsx/not-a-workbook.xlsx", format: "xlsx", category: "wrong-extension", producer: "generator (text)", licence,
      expect: { result: "error", error: "mismatch" }, rules: SAFE_RULES });
  }

  // Macro-enabled workbook: opens with its saved values; the macro project is ignored (never read or run).
  {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "simple.xlsx")));
    zip.file("xl/vbaProject.bin", Buffer.from("Placeholder, not real VBA."), { date });
    const types = await zip.file("[Content_Types].xml").async("string");
    zip.file("[Content_Types].xml", types.replace("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml", "application/vnd.ms-excel.sheet.macroEnabled.main+xml")
      .replace("</Types>", '<Default Extension="bin" ContentType="application/vnd.ms-office.vbaProject"/></Types>'), { date });
    write("xlsx/macro.xlsm", await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" }));
    record({ id: "xlsm-macro", file: "xlsx/macro.xlsm", format: "xlsm", category: "macro", producer: `${producer}, repackaged with JSZip`, licence,
      expect: { result: "open", sheets: ["Hello"], cells: [{ sheet: "Hello", ref: "B1", text: "42" }], macrosRemoved: true }, rules: SAFE_RULES });
  }
  // Template: same parts, template main type; opens like an ordinary workbook.
  {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "simple.xlsx")));
    const types = await zip.file("[Content_Types].xml").async("string");
    zip.file("[Content_Types].xml", types.replace("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml", "application/vnd.openxmlformats-officedocument.spreadsheetml.template.main+xml"), { date });
    write("xlsx/variant.xltx", await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" }));
    record({ id: "xltx-variant", file: "xlsx/variant.xltx", format: "xltx", category: "variant", producer: `${producer}, repackaged with JSZip`, licence,
      expect: { result: "open", sheets: ["Hello"], cells: [{ sheet: "Hello", ref: "B1", text: "42" }] }, rules: SAFE_RULES });
  }

  // Hostile: ZIP bomb (an extra 300 MB entry of zeros, about 300 KB compressed).
  {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "simple.xlsx")));
    zip.file("xl/media/bomb.bin", Buffer.alloc(300 * 1024 * 1024), { date, compression: "DEFLATE", compressionOptions: { level: 9 } });
    zip.forEach((_, f) => { f.date = date; });
    write("xlsx/attack-zip-bomb.xlsx", await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" }));
    record({ id: "attack-xlsx-zip-bomb", file: "xlsx/attack-zip-bomb.xlsx", format: "xlsx", category: "attack", producer: `${producer}, repackaged with JSZip`, licence,
      expect: { result: "error", error: "damaged" }, rules: SAFE_RULES, notes: "Must be refused by the archive limits without decompressing the 300 MB entry." });
  }

  // Hostile: XML external entity in the workbook part.
  {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "simple.xlsx")));
    const workbookXml = await zip.file("xl/workbook.xml").async("string");
    const doctype = `<!DOCTYPE workbook [<!ENTITY remote SYSTEM "${LISTENER}/xlsx-xxe/entity"><!ENTITY local SYSTEM "file:///C:/Windows/win.ini">]>`;
    zip.file("xl/workbook.xml", workbookXml.replace(/^(<\?xml[^>]*\?>)/, `$1${doctype}`).replace('name="Hello"', 'name="&remote;&local;"'), { date });
    write("xlsx/attack-xxe.xlsx", await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" }));
    record({ id: "attack-xlsx-xxe", file: "xlsx/attack-xxe.xlsx", format: "xlsx", category: "attack", producer: `${producer}, edited with JSZip`, licence,
      expect: { result: "error", error: "damaged" }, rules: SAFE_RULES, notes: "DTDs are prohibited; neither entity may be resolved." });
  }

  // Pictures and charts: a picture placed by exceljs, then two charts on the same sheet and a chart sheet added as
  // hand-written DrawingML (exceljs cannot write charts). Chart values are the chart's own cache.
  {
    const wb = workbook();
    const ws = wb.addWorksheet("Sales");
    ws.addRows([["Month", "North", "South"], ["Jan", 120, 80], ["Feb", 150, 95], ["Mar", 90, 130], ["Apr", 170, 110]]);
    ws.getCell("A7").value = "Hello pictures";
    const image = wb.addImage({ buffer: chartPng(), extension: "png" });
    ws.addImage(image, { tl: { col: 4, row: 0 }, ext: { width: 240, height: 120 }, editAs: "oneCell" });
    const zip = await JSZip.loadAsync(await wb.xlsx.writeBuffer());
    const drawingPath = Object.keys(zip.files).find(n => /^xl\/drawings\/drawing\d+\.xml$/.test(n));
    const relsPath = drawingPath.replace("drawings/", "drawings/_rels/") + ".rels";
    const frame = (id, from, to, rid, name) => `<xdr:twoCellAnchor><xdr:from><xdr:col>${from[0]}</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>${from[1]}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from>` +
      `<xdr:to><xdr:col>${to[0]}</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>${to[1]}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:to>` +
      `<xdr:graphicFrame macro=""><xdr:nvGraphicFramePr><xdr:cNvPr id="${id}" name="${name}"/><xdr:cNvGraphicFramePr/></xdr:nvGraphicFramePr><xdr:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/></xdr:xfrm>` +
      `<a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/chart"><c:chart xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:id="${rid}"/></a:graphicData></a:graphic></xdr:graphicFrame><xdr:clientData/></xdr:twoCellAnchor>`;
    let drawing = await zip.file(drawingPath).async("string");
    if (!drawing.includes('xmlns:a=')) drawing = drawing.replace("<xdr:wsDr ", '<xdr:wsDr xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" ');
    drawing = drawing.replace("</xdr:wsDr>", frame(10, [0, 8], [5, 22], "rIdChart1", "Sales by month") + frame(11, [6, 8], [11, 22], "rIdChart2", "January share") + "</xdr:wsDr>");
    zip.file(drawingPath, drawing);
    const chartRel = (id, n) => `<Relationship Id="${id}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/chart" Target="../charts/chart${n}.xml"/>`;
    zip.file(relsPath, (await zip.file(relsPath).async("string")).replace("</Relationships>", chartRel("rIdChart1", 1) + chartRel("rIdChart2", 2) + "</Relationships>"));
    const months = ["Jan", "Feb", "Mar", "Apr"];
    zip.file("xl/charts/chart1.xml", chartXml({ kind: "barChart", title: "Sales by month", categories: months, series: [["North", [120, 150, 90, 170], "4472C4"], ["South", [80, 95, 130, 110], "ED7D31"]] }));
    zip.file("xl/charts/chart2.xml", chartXml({ kind: "pieChart", title: "January share", categories: ["North", "South"], series: [["January", [120, 80]]], across: { cat: "Sales!$B$1:$C$1", val: "Sales!$B$2:$C$2" } }));
    zip.file("xl/charts/chart3.xml", chartXml({ kind: "lineChart", title: "Trend", categories: months, series: [["North", [120, 150, 90, 170], "70AD47"], ["South", [80, 95, 130, 110]]] }));
    // The chart sheet "Trend".
    zip.file("xl/chartsheets/sheet2.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><chartsheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheetPr/><sheetViews><sheetView workbookViewId="0"/></sheetViews><pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/><drawing r:id="rId1"/></chartsheet>`);
    zip.file("xl/chartsheets/_rels/sheet2.xml.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing" Target="../drawings/drawing90.xml"/></Relationships>`);
    zip.file("xl/drawings/drawing90.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">` +
      `<xdr:absoluteAnchor><xdr:pos x="0" y="0"/><xdr:ext cx="8666667" cy="6293304"/><xdr:graphicFrame macro=""><xdr:nvGraphicFramePr><xdr:cNvPr id="2" name="Trend"/><xdr:cNvGraphicFramePr/></xdr:nvGraphicFramePr><xdr:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/></xdr:xfrm>` +
      `<a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/chart"><c:chart xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" r:id="rId1"/></a:graphicData></a:graphic></xdr:graphicFrame><xdr:clientData/></xdr:absoluteAnchor></xdr:wsDr>`);
    zip.file("xl/drawings/_rels/drawing90.xml.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${chartRel("rId1", 3)}</Relationships>`);
    let book = await zip.file("xl/workbook.xml").async("string");
    book = book.replace("</sheets>", '<sheet name="Trend" sheetId="90" r:id="rIdChartSheet"/></sheets>');
    zip.file("xl/workbook.xml", book);
    zip.file("xl/_rels/workbook.xml.rels", (await zip.file("xl/_rels/workbook.xml.rels").async("string")).replace("</Relationships>",
      '<Relationship Id="rIdChartSheet" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/chartsheet" Target="chartsheets/sheet2.xml"/></Relationships>'));
    const override = (part, type) => `<Override PartName="/${part}" ContentType="application/vnd.openxmlformats-officedocument.${type}"/>`;
    zip.file("[Content_Types].xml", (await zip.file("[Content_Types].xml").async("string")).replace("</Types>",
      override("xl/charts/chart1.xml", "drawingml.chart+xml") + override("xl/charts/chart2.xml", "drawingml.chart+xml") + override("xl/charts/chart3.xml", "drawingml.chart+xml") +
      override("xl/chartsheets/sheet2.xml", "spreadsheetml.chartsheet+xml") + override("xl/drawings/drawing90.xml", "drawing+xml") + "</Types>"));
    write("xlsx/drawings.xlsx", await stable(await zip.generateAsync({ type: "nodebuffer" })));
    record({ id: "xlsx-drawings", file: "xlsx/drawings.xlsx", format: "xlsx", category: "complex", producer: `${producer}, charts added as hand-written DrawingML with JSZip`, licence,
      expect: { result: "open", sheets: ["Sales", "Trend"], text: ["Hello pictures"],
        drawings: [{ sheet: "Sales", pictures: 1, charts: ["column:Sales by month:2", "pie:January share:1"], values: ["120,150,90,170", "80,95,130,110"], categories: "Jan,Feb,Mar,Apr", values2: ["120,80"], categories2: "North,South" }, { sheet: "Trend", chartSheet: true, charts: ["line:Trend:2"] }] },
      rules: SAFE_RULES, notes: "The picture is the corpus's own PNG. Charts are drawn from their cached values; the chart sheet shows its chart filling the view." });
  }

  // Hostile: a linked picture (stored outside the file) pointing at the request listener and at a network share.
  {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "drawings.xlsx")));
    const drawingPath = Object.keys(zip.files).find(n => /^xl\/drawings\/drawing\d\.xml$/.test(n));
    const relsPath = drawingPath.replace("drawings/", "drawings/_rels/") + ".rels";
    const pic = (id, rid) => `<xdr:oneCellAnchor><xdr:from><xdr:col>1</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>${id}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:ext cx="952500" cy="476250"/>` +
      `<xdr:pic><xdr:nvPicPr><xdr:cNvPr id="${id}" name="Linked ${id}"/><xdr:cNvPicPr/></xdr:nvPicPr><xdr:blipFill><a:blip xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:link="${rid}"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill>` +
      `<xdr:spPr><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/></xdr:oneCellAnchor>`;
    zip.file(drawingPath, (await zip.file(drawingPath).async("string")).replace("</xdr:wsDr>", pic(30, "rIdLink1") + pic(31, "rIdLink2") + "</xdr:wsDr>"));
    const link = (id, target) => `<Relationship Id="${id}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="${target}" TargetMode="External"/>`;
    zip.file(relsPath, (await zip.file(relsPath).async("string")).replace("</Relationships>",
      link("rIdLink1", `${LISTENER}/xlsx-linked-picture/image.png`) + link("rIdLink2", `file:///${WEBDAV_UNC.replace(/\\/g, "/")}/image.png`) + "</Relationships>"));
    write("xlsx/attack-linked-picture.xlsx", await stable(await zip.generateAsync({ type: "nodebuffer" })));
    record({ id: "attack-xlsx-linked-picture", file: "xlsx/attack-linked-picture.xlsx", format: "xlsx", category: "attack", producer: `${producer}, edited with JSZip`, licence,
      expect: { result: "open", sheets: ["Sales", "Trend"], text: ["Hello pictures", "linked picture"], drawings: [{ sheet: "Sales", pictures: 1 }] },
      rules: SAFE_RULES, notes: "Two linked pictures (web address and network share) must never be fetched; the notice says they are not loaded." });
  }

  if (large) {
    const target = path.join(CORPUS, "generated", "xlsx-large-500k-rows.xlsx");
    fs.mkdirSync(path.dirname(target), { recursive: true });
    const wb = new ExcelJS.stream.xlsx.WorkbookWriter({ filename: target, useSharedStrings: false, useStyles: true });
    const ws = wb.addWorksheet("Large");
    ws.addRow(["Row", "Region", "Amount", "Share", "Code", "Note"]).commit();
    const regions = ["North", "South", "East", "West", "Sindh"];
    for (let i = 1; i <= 500000; i++) ws.addRow([i, regions[i % 5], (i * 7919) % 100000 / 100, (i % 1000) / 1000, String(i).padStart(8, "0"), i === 500000 ? "Hello last row" : `note ${i % 97}`]).commit();
    ws.commit(); await wb.commit();
    record({ id: "xlsx-large", file: "generated/xlsx-large-500k-rows.xlsx", format: "xlsx", category: "large", producer, licence, generated: true,
      expect: { result: "open", sheets: ["Large"], text: ["Region"] }, rules: SAFE_RULES,
      notes: "Performance target: first sheet opens without exhausting memory. The preview currently shows the first 10,000 rows with a notice." });
  }
}
