import ExcelJS from "exceljs";
import JSZip from "jszip";
import officeCrypto from "officecrypto-tool";
import CFB from "cfb";
import fs from "node:fs";
import path from "node:path";
import { write, record, packageVersion, LISTENER, WEBDAV_UNC, SAFE_RULES, CORPUS } from "./lib.mjs";

const producer = `exceljs ${packageVersion("exceljs")} (Node)`;
const licence = "Generated by this repository; no third-party content";
const date = new Date(Date.UTC(2026, 8, 27));

function workbook() {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Plain Viewer corpus"; wb.created = date; wb.modified = date;
  return wb;
}

// ZIP output from exceljs embeds the current time in entry headers; rewrite entries with a fixed date so
// regenerated fixtures are identical.
async function stable(buffer) {
  const zip = await JSZip.loadAsync(buffer);
  zip.forEach((_, file) => { file.date = date; });
  return zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE", compressionOptions: { level: 6 } });
}

export async function generateXlsx({ large }) {
  // Simple
  {
    const wb = workbook();
    const ws = wb.addWorksheet("Hello");
    ws.getCell("A1").value = "Hello spreadsheet";
    ws.getCell("B1").value = 42;
    ws.getCell("A2").value = "Second row";
    ws.getCell("B2").value = 3.14;
    write("xlsx/simple.xlsx", await stable(await wb.xlsx.writeBuffer()));
    record({ id: "xlsx-simple", file: "xlsx/simple.xlsx", format: "xlsx", category: "simple", producer, licence,
      expect: { result: "open", sheets: ["Hello"], text: ["Hello spreadsheet"], cells: [{ sheet: "Hello", ref: "B1", text: "42" }, { sheet: "Hello", ref: "B2", text: "3.14" }] },
      rules: SAFE_RULES });
  }

  // Complex: formats, merge, frozen panes, widths, cached and missing formula results, RTL, hidden sheets.
  {
    const wb = workbook();
    const ws = wb.addWorksheet("Summary", { views: [{ state: "frozen", xSplit: 1, ySplit: 2 }] });
    ws.columns = [{ width: 16 }, { width: 14 }, { width: 10 }, { width: 12 }, { width: 8 }, { width: 12 }];
    ws.mergeCells("A1:D1");
    ws.getCell("A1").value = "Hello workbook summary";
    ws.getRow(2).values = ["Item", "Amount", "Share", "Date", "Time", "Code"];
    const money = '"$"#,##0.00;[Red]-"$"#,##0.00';
    const rows = [["Alpha", 10, 0.1, Date.UTC(2026, 8, 27), 0.5, "00123"], ["Beta", 20, 0.2, Date.UTC(2026, 0, 15), 0.75, "00456"],
      ["Gamma", 30, 0.3, Date.UTC(2025, 11, 31), 0.25, "Hello cell"], ["Delta", -40, 0.4, Date.UTC(2024, 1, 29), 0, "=1+1"]];
    rows.forEach((values, i) => {
      const r = 3 + i;
      ws.getCell(`A${r}`).value = values[0];
      ws.getCell(`B${r}`).value = values[1]; ws.getCell(`B${r}`).numFmt = money;
      ws.getCell(`C${r}`).value = values[2]; ws.getCell(`C${r}`).numFmt = "0.0%";
      ws.getCell(`D${r}`).value = new Date(values[3]); ws.getCell(`D${r}`).numFmt = "yyyy-mm-dd";
      ws.getCell(`E${r}`).value = values[4]; ws.getCell(`E${r}`).numFmt = "hh:mm";
      ws.getCell(`F${r}`).value = values[5];                        // text, including leading zeros and "=1+1"
    });
    ws.getCell("A7").value = "Total";
    ws.getCell("B7").value = { formula: "SUM(B3:B6)", result: 20 }; ws.getCell("B7").numFmt = money;
    ws.getCell("A8").value = "Missing";
    ws.getCell("B8").value = { formula: "B3*2" };                     // no cached result on purpose
    ws.getCell("A9").value = "Web service";
    ws.getCell("B9").value = { formula: `WEBSERVICE("${LISTENER}/xlsx-webservice")`, result: "cached-ok" };
    ws.getCell("A10").value = "External";
    ws.getCell("B10").value = { formula: `'[${WEBDAV_UNC}\\book.xlsx]Sheet1'!A1`, result: 7 };
    ws.getCell("A11").value = "Flags";
    ws.getCell("B11").value = true;
    ws.getCell("C11").value = { error: "#DIV/0!" };
    ws.getCell("A12").value = "Big";
    ws.getCell("B12").value = 1234567.891; ws.getCell("B12").numFmt = "#,##0.00";
    ws.getCell("A13").value = "General";
    ws.getCell("B13").value = 0.1 + 0.2;

    const rtl = wb.addWorksheet("Urdu", { views: [{ rightToLeft: true }] });
    rtl.columns = [{ width: 36 }];
    ["اردو: یہ ایک دستاویز ہے", "سنڌي: سلام دنيا", "العربية: مرحبا بالعالم", "中文：你好世界", "日本語：こんにちは"].forEach((t, i) => { rtl.getCell(`A${i + 1}`).value = t; });

    wb.addWorksheet("HiddenData", { state: "hidden" }).getCell("A1").value = "Secret hidden value";
    wb.addWorksheet("VeryHidden", { state: "veryHidden" }).getCell("A1").value = "Very hidden value";
    write("xlsx/complex.xlsx", await stable(await wb.xlsx.writeBuffer()));
    const cell = (ref, text) => ({ sheet: "Summary", ref, text });
    record({ id: "xlsx-complex", file: "xlsx/complex.xlsx", format: "xlsx", category: "complex", producer, licence,
      expect: {
        result: "open", sheets: ["Summary", "Urdu"], hiddenSheetsNotShown: ["HiddenData", "VeryHidden"], culture: "en-US",
        text: ["Hello workbook summary", "Hello cell"],
        cells: [cell("A1", "Hello workbook summary"), cell("B3", "$10.00"), cell("C3", "10.0%"), cell("D3", "2026-09-27"), cell("E3", "12:00"),
          cell("F3", "00123"), cell("F6", "=1+1"), cell("B6", "-$40.00"), cell("B7", "$20.00"), cell("B8", "Result unavailable"),
          cell("B9", "cached-ok"), cell("B10", "7"), cell("B11", "TRUE"), cell("C11", "#DIV/0!"), cell("B12", "1,234,567.89"), cell("B13", "0.3"),
          { sheet: "Urdu", ref: "A2", text: "سنڌي: سلام دنيا" }],
        merges: [{ sheet: "Summary", range: "A1:D1" }], frozen: { sheet: "Summary", rows: 2, columns: 1 }, rightToLeft: ["Urdu"]
      },
      rules: { ...SAFE_RULES, formulas: "Never recalculated; WEBSERVICE and the external workbook reference must not be contacted" } });
  }

  // Empty worksheet
  {
    const wb = workbook(); wb.addWorksheet("Blank");
    write("xlsx/empty-sheet.xlsx", await stable(await wb.xlsx.writeBuffer()));
    record({ id: "xlsx-empty-sheet", file: "xlsx/empty-sheet.xlsx", format: "xlsx", category: "empty", producer, licence,
      expect: { result: "open", sheets: ["Blank"], notice: "This sheet is empty." }, rules: SAFE_RULES });
  }

  // Password protected (Agile encryption). Test password, not a secret.
  {
    const plain = fs.readFileSync(path.join(CORPUS, "xlsx", "simple.xlsx"));
    write("xlsx/password.xlsx", officeCrypto.encrypt(plain, { password: "viewer-test" }));
    record({ id: "xlsx-password", file: "xlsx/password.xlsx", format: "xlsx", category: "password",
      producer: `${producer}, encrypted with officecrypto-tool ${packageVersion("officecrypto-tool")}`, licence, password: "viewer-test",
      expect: { result: "error", error: "password" }, rules: SAFE_RULES,
      notes: "v1 only needs a clear explanation for protected Office files; entering a password is not required." });
  }

  // An older binary container (not encrypted) saved with an .xlsx name.
  {
    const container = CFB.utils.cfb_new();
    CFB.utils.cfb_add(container, "Workbook", Buffer.from("Not a real BIFF stream; container only."));
    write("xlsx/old-format-renamed.xlsx", Buffer.from(CFB.write(container, { type: "buffer" })));
    record({ id: "xlsx-old-format", file: "xlsx/old-format-renamed.xlsx", format: "xlsx", category: "wrong-extension", producer: `cfb ${packageVersion("cfb")} (Node)`, licence,
      expect: { result: "error", error: "mismatch" }, rules: SAFE_RULES });
  }

  // Damaged, empty and mislabelled files
  {
    const full = fs.readFileSync(path.join(CORPUS, "xlsx", "complex.xlsx"));
    write("xlsx/damaged-truncated.xlsx", full.subarray(0, Math.floor(full.length * 0.5)));
    record({ id: "xlsx-truncated", file: "xlsx/damaged-truncated.xlsx", format: "xlsx", category: "damaged", producer: `${producer}, then truncated`, licence,
      expect: { result: "error", error: "damaged" }, rules: SAFE_RULES });
    write("xlsx/zero-byte.xlsx", Buffer.alloc(0));
    record({ id: "xlsx-zero-byte", file: "xlsx/zero-byte.xlsx", format: "xlsx", category: "empty", producer: "generator (empty file)", licence,
      expect: { result: "error", error: "empty" }, rules: SAFE_RULES });
    write("xlsx/not-a-workbook.xlsx", "Plain text saved with an .xlsx name.\r\n");
    record({ id: "xlsx-mismatch", file: "xlsx/not-a-workbook.xlsx", format: "xlsx", category: "wrong-extension", producer: "generator (text)", licence,
      expect: { result: "error", error: "mismatch" }, rules: SAFE_RULES });
  }

  // Macro-enabled workbook: opens with its saved values; the macro project is ignored (never read or run).
  {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "simple.xlsx")));
    zip.file("xl/vbaProject.bin", Buffer.from("Placeholder, not real VBA."), { date });
    const types = await zip.file("[Content_Types].xml").async("string");
    zip.file("[Content_Types].xml", types.replace("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml", "application/vnd.ms-excel.sheet.macroEnabled.main+xml")
      .replace("</Types>", '<Default Extension="bin" ContentType="application/vnd.ms-office.vbaProject"/></Types>'), { date });
    write("xlsx/macro.xlsm", await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" }));
    record({ id: "xlsm-macro", file: "xlsx/macro.xlsm", format: "xlsm", category: "macro", producer: `${producer}, repackaged with JSZip`, licence,
      expect: { result: "open", sheets: ["Hello"], cells: [{ sheet: "Hello", ref: "B1", text: "42" }], macrosRemoved: true }, rules: SAFE_RULES });
  }
  // Template: same parts, template main type; opens like an ordinary workbook.
  {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "simple.xlsx")));
    const types = await zip.file("[Content_Types].xml").async("string");
    zip.file("[Content_Types].xml", types.replace("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml", "application/vnd.openxmlformats-officedocument.spreadsheetml.template.main+xml"), { date });
    write("xlsx/variant.xltx", await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" }));
    record({ id: "xltx-variant", file: "xlsx/variant.xltx", format: "xltx", category: "variant", producer: `${producer}, repackaged with JSZip`, licence,
      expect: { result: "open", sheets: ["Hello"], cells: [{ sheet: "Hello", ref: "B1", text: "42" }] }, rules: SAFE_RULES });
  }

  // Hostile: ZIP bomb (an extra 300 MB entry of zeros, about 300 KB compressed).
  {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "simple.xlsx")));
    zip.file("xl/media/bomb.bin", Buffer.alloc(300 * 1024 * 1024), { date, compression: "DEFLATE", compressionOptions: { level: 9 } });
    zip.forEach((_, f) => { f.date = date; });
    write("xlsx/attack-zip-bomb.xlsx", await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" }));
    record({ id: "attack-xlsx-zip-bomb", file: "xlsx/attack-zip-bomb.xlsx", format: "xlsx", category: "attack", producer: `${producer}, repackaged with JSZip`, licence,
      expect: { result: "error", error: "damaged" }, rules: SAFE_RULES, notes: "Must be refused by the archive limits without decompressing the 300 MB entry." });
  }

  // Hostile: XML external entity in the workbook part.
  {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "simple.xlsx")));
    const workbookXml = await zip.file("xl/workbook.xml").async("string");
    const doctype = `<!DOCTYPE workbook [<!ENTITY remote SYSTEM "${LISTENER}/xlsx-xxe/entity"><!ENTITY local SYSTEM "file:///C:/Windows/win.ini">]>`;
    zip.file("xl/workbook.xml", workbookXml.replace(/^(<\?xml[^>]*\?>)/, `$1${doctype}`).replace('name="Hello"', 'name="&remote;&local;"'), { date });
    write("xlsx/attack-xxe.xlsx", await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" }));
    record({ id: "attack-xlsx-xxe", file: "xlsx/attack-xxe.xlsx", format: "xlsx", category: "attack", producer: `${producer}, edited with JSZip`, licence,
      expect: { result: "error", error: "damaged" }, rules: SAFE_RULES, notes: "DTDs are prohibited; neither entity may be resolved." });
  }

  if (large) {
    const target = path.join(CORPUS, "generated", "xlsx-large-500k-rows.xlsx");
    fs.mkdirSync(path.dirname(target), { recursive: true });
    const wb = new ExcelJS.stream.xlsx.WorkbookWriter({ filename: target, useSharedStrings: false, useStyles: true });
    const ws = wb.addWorksheet("Large");
    ws.addRow(["Row", "Region", "Amount", "Share", "Code", "Note"]).commit();
    const regions = ["North", "South", "East", "West", "Sindh"];
    for (let i = 1; i <= 500000; i++) ws.addRow([i, regions[i % 5], (i * 7919) % 100000 / 100, (i % 1000) / 1000, String(i).padStart(8, "0"), i === 500000 ? "Hello last row" : `note ${i % 97}`]).commit();
    ws.commit(); await wb.commit();
    record({ id: "xlsx-large", file: "generated/xlsx-large-500k-rows.xlsx", format: "xlsx", category: "large", producer, licence, generated: true,
      expect: { result: "open", sheets: ["Large"], text: ["Region"] }, rules: SAFE_RULES,
      notes: "Performance target: first sheet opens without exhausting memory. The preview currently shows the first 10,000 rows with a notice." });
  }
}
